# ruff: noqa: E501
# src/alibaba_scraper/production_ui.py
"""Self-contained production operations dashboard assets."""

OPS_CSS = r"""
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#e9eef6;background:#0a1017}*{box-sizing:border-box}body{margin:0;background:#0a1017;color:#e9eef6}.wrap{max-width:1500px;margin:auto;padding:20px}header{display:flex;justify-content:space-between;gap:16px;align-items:center}.brand h1{margin:0}.muted{color:#8ea0b5}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:16px 0}.card,.panel{background:#111b26;border:1px solid #223244;border-radius:12px;padding:14px}.metric b{display:block;font-size:24px;margin-top:4px}.tabs{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0}button,input,select,textarea{background:#0e1721;color:#e9eef6;border:1px solid #30465d;border-radius:8px;padding:9px}button{cursor:pointer}.active{background:#203c55}.danger{border-color:#7d4141}.ok{color:#7bdca7}.err{color:#ff8f8f}.hidden{display:none}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.toolbar input{flex:1;min-width:150px}.forms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.forms label{display:flex;flex-direction:column;gap:4px;color:#9bb0c5}.full{grid-column:span 2}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border-bottom:1px solid #203040;text-align:left}.chart{min-height:230px;background:#0b141e;border-radius:9px;padding:8px}.result{white-space:pre-wrap;background:#081019;padding:10px;border-radius:8px;overflow:auto}.keybar{display:flex;gap:8px;align-items:center}.keybar input{min-width:260px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.forms{grid-template-columns:1fr}.full{grid-column:span 1}}
"""

OPS_JS = r"""
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function key(){return sessionStorage.getItem('alibabaApiKey')||''}async function saveKey(){sessionStorage.setItem('alibabaApiKey',$('#api-key').value.trim());await api('/api/auth/session',{method:'POST'});refresh()}
async function api(path,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(key())headers['X-API-Key']=key();const r=await fetch(path,{...opts,headers});if(r.status===401)throw new Error('API key required or invalid');if(r.status===403)throw new Error('API key lacks required scope');if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function tab(n){$$('[data-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==n));$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===n))}
function bars(el,rows,labelKey,valueKey){const m=Math.max(1,...rows.map(r=>Number(r[valueKey]||0)));el.innerHTML=rows.map(r=>`<div style="display:grid;grid-template-columns:150px 1fr 50px;gap:8px;align-items:center;margin:7px 0"><span>${esc(r[labelKey])}</span><div style="height:18px;background:#0c1219;border-radius:4px"><div style="height:18px;width:${Math.max(2,Number(r[valueKey]||0)/m*100)}%;background:#3e6d94;border-radius:4px"></div></div><b>${esc(r[valueKey])}</b></div>`).join('')}
function line(el,rows){if(!rows.length){el.textContent='No history yet';return}const vals=rows.map(r=>Number(r.price_min)).filter(Number.isFinite);if(!vals.length){el.textContent='No numeric prices';return}const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(.0001,max-min);const pts=vals.map((v,i)=>`${20+i*(560/Math.max(1,vals.length-1))},${200-(v-min)/range*160}`).join(' ');el.innerHTML=`<svg viewBox="0 0 600 230" width="100%"><polyline fill="none" stroke="currentColor" stroke-width="3" points="${pts}"/><text x="20" y="220" fill="currentColor">${esc(rows[0].currency||'')} ${min.toFixed(2)} → ${max.toFixed(2)}</text></svg>`}
async function health(){const h=await api('/api/health');$('#health-json').textContent=JSON.stringify(h,null,2);$('#m-schema').textContent=h.schema_version;$('#m-requests').textContent=h.telemetry.requests_total;$('#m-errors').textContent=h.telemetry.request_errors_total;$('#m-delivery').textContent=h.alert_delivery.failed}
async function analytics(){const a=await api('/api/analytics');bars($('#category-chart'),a.categories,'category','products');bars($('#score-chart'),a.score_distribution,'bucket','count')}
async function compare(){const ids=$('#compare-ids').value.split(',').map(x=>x.trim()).filter(Boolean);const r=await api('/api/comparisons/products',{method:'POST',body:JSON.stringify({identifiers:ids})});$('#compare-body').innerHTML=r.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.supplier_name)}</td><td>${esc(x.price_min)} ${esc(x.currency)}</td><td>${esc(x.moq)}</td><td>${esc(x.active_score??'-')}</td><td>${esc(x.category_score??'-')}</td><td><b>${esc(x.effective_score??'-')}</b></td></tr>`).join('')}
async function history(){const id=$('#history-id').value.trim();const r=await api('/api/charts/price-history/'+encodeURIComponent(id));line($('#history-chart'),r)}
async function scenarios(){const r=await api('/api/landed-cost/scenarios');$('#scenario-body').innerHTML=r.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.product_key||'-')}</td><td>${esc(x.result.landed_total)} ${esc(x.result.currency)}</td><td>${esc(x.result.landed_per_unit)}</td><td><button class="danger" onclick="deleteScenario(${x.id})">Delete</button></td></tr>`).join('')}
async function saveScenario(){const body={name:$('#sc-name').value,product_key:$('#sc-product').value||null,values:{currency:$('#sc-currency').value,unit_price:+$('#sc-price').value,quantity:+$('#sc-qty').value,shipping:+$('#sc-shipping').value,duty_rate_pct:+$('#sc-duty').value,tax_rate_pct:+$('#sc-tax').value,packaging_per_unit:+$('#sc-pack').value}};await api('/api/landed-cost/scenarios',{method:'POST',body:JSON.stringify(body)});await scenarios()}async function deleteScenario(id){await api('/api/landed-cost/scenarios/'+id,{method:'DELETE'});await scenarios()}
async function bindings(){const [b,p]=await Promise.all([api('/api/scoring/category-bindings'),api('/api/scoring/profiles')]);$('#bind-profile').innerHTML=p.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('#binding-body').innerHTML=b.map(x=>`<tr><td>${esc(x.category_pattern)}</td><td>#${x.profile_id}</td><td>${x.priority}</td><td>${x.enabled?'on':'off'}</td><td><button class="danger" onclick="deleteBinding(${x.id})">Delete</button></td></tr>`).join('')}
async function addBinding(){await api('/api/scoring/category-bindings',{method:'POST',body:JSON.stringify({category_pattern:$('#bind-pattern').value,profile_id:+$('#bind-profile').value,priority:+$('#bind-priority').value,enabled:true})});await api('/api/scoring/category-rescore',{method:'POST'});await bindings();await analytics()}async function deleteBinding(id){await api('/api/scoring/category-bindings/'+id,{method:'DELETE'});await bindings()}
async function sinks(){const r=await api('/api/admin/alert-sinks');$('#sink-body').innerHTML=r.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.kind)}</td><td>${esc(x.endpoint)}</td><td>${esc(x.minimum_severity)}</td><td>${x.enabled?'on':'off'}</td><td><button class="danger" onclick="deleteSink(${x.id})">Delete</button></td></tr>`).join('')}
async function addSink(){const body={name:$('#sink-name').value,kind:'webhook',endpoint:$('#sink-url').value,secret:$('#sink-secret').value||null,event_kinds:$('#sink-kinds').value.split(',').map(x=>x.trim()).filter(Boolean),minimum_severity:$('#sink-severity').value,enabled:true};await api('/api/admin/alert-sinks',{method:'POST',body:JSON.stringify(body)});await sinks()}async function deleteSink(id){await api('/api/admin/alert-sinks/'+id,{method:'DELETE'});await sinks()}async function deliver(){const r=await api('/api/admin/alert-sinks/deliver',{method:'POST'});$('#delivery-result').textContent=JSON.stringify(r,null,2);await health()}
async function keys(){const r=await api('/api/admin/api-keys');$('#keys-body').innerHTML=r.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.key_prefix)}…</td><td>${esc(x.scopes.join(','))}</td><td>${x.enabled?'on':'off'}</td><td>${esc(x.last_used_at||'-')}</td><td><button class="danger" onclick="revokeKey(${x.id})">Revoke</button></td></tr>`).join('')}async function revokeKey(id){await api('/api/admin/api-keys/'+id,{method:'DELETE'});await keys()}
async function refresh(){try{await Promise.all([health(),analytics(),scenarios(),bindings(),sinks(),keys()]);$('#status').textContent='authenticated';$('#status').className='ok'}catch(e){$('#status').textContent=e.message;$('#status').className='err'}}
window.deleteScenario=deleteScenario;window.deleteBinding=deleteBinding;window.deleteSink=deleteSink;window.revokeKey=revokeKey;document.addEventListener('DOMContentLoaded',()=>{$('#api-key').value=key();$('#save-key').onclick=saveKey;$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#compare-go').onclick=compare;$('#history-go').onclick=history;$('#scenario-save').onclick=saveScenario;$('#binding-add').onclick=addBinding;$('#sink-add').onclick=addSink;$('#sink-deliver').onclick=deliver;tab('health');if(key())refresh()});
"""

OPS_HTML = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AlibabaScraper Operations</title><link rel="stylesheet" href="/assets/ops.css"></head><body><div class="wrap"><header><div class="brand"><h1>AlibabaScraper Operations</h1><div class="muted">Production health, comparisons, scenarios, policies and delivery</div></div><div class="keybar"><input id="api-key" type="password" placeholder="X-API-Key"><button id="save-key">Use key</button><span id="status" class="muted">key required</span><a href="/classic" style="color:#9fc8eb">Control dashboard</a></div></header><div class="grid"><div class="card metric">Schema<b id="m-schema">-</b></div><div class="card metric">Requests<b id="m-requests">-</b></div><div class="card metric">5xx errors<b id="m-errors">-</b></div><div class="card metric">Delivery failures<b id="m-delivery">-</b></div></div><div class="tabs"><button data-tab="health">Health</button><button data-tab="analytics">Charts</button><button data-tab="compare">Compare</button><button data-tab="scenarios">Landed scenarios</button><button data-tab="bindings">Category scoring</button><button data-tab="sinks">Alert sinks</button><button data-tab="keys">API keys</button></div>
<section data-panel="health" class="panel"><h2>Health & telemetry</h2><pre id="health-json" class="result"></pre></section>
<section data-panel="analytics" class="panel"><h2>Catalog analytics</h2><div class="grid"><div class="card" style="grid-column:span 2"><h3>Top categories</h3><div id="category-chart" class="chart"></div></div><div class="card" style="grid-column:span 2"><h3>Category-profile score distribution</h3><div id="score-chart" class="chart"></div></div></div></section>
<section data-panel="compare" class="panel"><h2>Product comparison</h2><div class="toolbar"><input id="compare-ids" placeholder="product IDs or keys, comma separated"><button id="compare-go">Compare</button></div><div class="table"><table><thead><tr><th>Product</th><th>Supplier</th><th>Price</th><th>MOQ</th><th>Active</th><th>Category</th><th>Effective</th></tr></thead><tbody id="compare-body"></tbody></table></div><h3>Price history</h3><div class="toolbar"><input id="history-id" placeholder="product ID or key"><button id="history-go">Chart</button></div><div id="history-chart" class="chart"></div></section>
<section data-panel="scenarios" class="panel"><h2>Saved landed-cost scenarios</h2><div class="forms"><label>Name<input id="sc-name"></label><label>Product key<input id="sc-product"></label><label>Currency<input id="sc-currency" value="USD"></label><label>Unit price<input id="sc-price" type="number" step="0.01"></label><label>Quantity<input id="sc-qty" type="number" value="1"></label><label>Shipping<input id="sc-shipping" type="number" value="0"></label><label>Duty %<input id="sc-duty" type="number" value="0"></label><label>Tax %<input id="sc-tax" type="number" value="0"></label><label>Packaging/unit<input id="sc-pack" type="number" value="0"></label><div><button id="scenario-save">Save / update</button></div></div><div class="table"><table><thead><tr><th>Name</th><th>Product</th><th>Total</th><th>Per unit</th><th></th></tr></thead><tbody id="scenario-body"></tbody></table></div></section>
<section data-panel="bindings" class="panel"><h2>Category-specific scoring profiles</h2><div class="toolbar"><input id="bind-pattern" placeholder="e.g. *solar*"><select id="bind-profile"></select><input id="bind-priority" type="number" value="100"><button id="binding-add">Bind + rescore</button></div><div class="table"><table><thead><tr><th>Pattern</th><th>Profile</th><th>Priority</th><th>Enabled</th><th></th></tr></thead><tbody id="binding-body"></tbody></table></div></section>
<section data-panel="sinks" class="panel"><h2>External alert delivery</h2><div class="forms"><label>Name<input id="sink-name"></label><label>Webhook URL<input id="sink-url"></label><label>Signing secret<input id="sink-secret" type="password"></label><label>Event kinds<input id="sink-kinds" placeholder="high_score,watchlist_change"></label><label>Minimum severity<select id="sink-severity"><option>info</option><option>warning</option><option>error</option></select></label><div><button id="sink-add">Add webhook</button><button id="sink-deliver">Deliver pending now</button></div></div><pre id="delivery-result" class="result"></pre><div class="table"><table><thead><tr><th>Name</th><th>Kind</th><th>Endpoint</th><th>Minimum</th><th>Enabled</th><th></th></tr></thead><tbody id="sink-body"></tbody></table></div></section>
<section data-panel="keys" class="panel"><h2>API keys</h2><p class="muted">Create new keys from the local CLI so the plaintext secret is never returned to an unauthenticated browser.</p><div class="table"><table><thead><tr><th>Name</th><th>Prefix</th><th>Scopes</th><th>Enabled</th><th>Last used</th><th></th></tr></thead><tbody id="keys-body"></tbody></table></div></section>
</div><script src="/assets/ops.js"></script></body></html>"""
