# ruff: noqa: E501
# src/alibaba_scraper/webui.py
"""Self-contained browser dashboard assets served by FastAPI."""

DASHBOARD_CSS = r"""
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#e8eef6;background:#0b1118}
*{box-sizing:border-box}body{margin:0;background:#0b1118;color:#e8eef6}.wrap{max-width:1440px;margin:auto;padding:22px}
header{display:flex;gap:18px;align-items:center;justify-content:space-between;margin-bottom:18px}.brand h1{margin:0;font-size:24px}.muted{color:#8ea0b5}.grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:12px}.card{background:#111b26;border:1px solid #223244;border-radius:12px;padding:15px}.metric b{font-size:25px;display:block}.span2{grid-column:span 2}.span3{grid-column:span 3}.span6{grid-column:span 6}nav{display:flex;gap:6px;flex-wrap:wrap;margin:18px 0}button,input,select{background:#111b26;color:#e8eef6;border:1px solid #30465d;border-radius:8px;padding:9px 11px}button{cursor:pointer}button:hover{border-color:#75a7d7}.active{background:#1d3851}.danger{border-color:#7d4141}.ok{color:#7bdca7}.warn{color:#f4c66e}.err{color:#ff8f8f}.hidden{display:none!important}.panel{background:#0e1721;border:1px solid #223244;border-radius:12px;padding:16px;margin-bottom:16px}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.toolbar input{min-width:150px;flex:1}table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;padding:9px;border-bottom:1px solid #213142;vertical-align:top}th{color:#91a7be;font-weight:600}.table-wrap{overflow:auto}.score{font-weight:700}.badge{display:inline-block;padding:2px 7px;border-radius:999px;background:#1c2a38}.forms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.forms label{display:flex;flex-direction:column;gap:5px;color:#9bb0c5}.forms .full{grid-column:span 2}.result{white-space:pre-wrap;background:#081019;padding:12px;border-radius:8px;min-height:40px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.span2,.span3,.span6{grid-column:span 2}.forms{grid-template-columns:1fr}.forms .full{grid-column:span 1}}
"""

DASHBOARD_JS = r"""
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function esc(v){return String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function tab(name){$$('[data-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==name));$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));}
async function summary(){const s=await api('/api/dashboard');$('#m-products').textContent=s.products;$('#m-suppliers').textContent=s.suppliers;$('#m-watchlists').textContent=s.watchlists;$('#m-running').textContent=s.running_jobs;$('#m-alerts').textContent=s.unread_alerts;$('#m-score').textContent=s.top_score??'-';$('#profile-name').textContent=s.active_profile.name;}
async function products(){const q=new URLSearchParams();[['query','#pq'],['min_score','#pmin'],['max_price','#pmax'],['currency','#pcurrency']].forEach(([k,s])=>{if($(s).value)q.set(k,$(s).value)});const rows=await api('/api/products?'+q);$('#products-body').innerHTML=rows.map(r=>`<tr><td class="score">${esc(r.score??'-')}</td><td>${esc(r.title)}</td><td>${esc(r.supplier_name)}</td><td>${esc(r.price_min??'-')} ${esc(r.currency??'')}</td><td>${esc(r.moq??'-')} ${esc(r.moq_unit??'')}</td><td><button onclick="productDetail('${esc(r.product_key)}')">Open</button></td></tr>`).join('');}
async function productDetail(id){const r=await api('/api/products/'+encodeURIComponent(id));$('#product-detail').textContent=JSON.stringify(r,null,2);}
async function suppliers(){const rows=await api('/api/suppliers');$('#suppliers-body').innerHTML=rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.country??'-')}</td><td>${r.product_count}</td><td><button onclick="supplierProducts('${esc(r.supplier_key)}')">Products</button></td></tr>`).join('');}
async function supplierProducts(id){const r=await api('/api/suppliers/'+encodeURIComponent(id)+'/products');$('#supplier-detail').textContent=JSON.stringify(r,null,2);}
async function jobs(){const rows=await api('/api/jobs');const live=await api('/api/runtime');const keys=new Set(live.filter(x=>['queued','running'].includes(x.status)).map(x=>x.key));$('#jobs-body').innerHTML=rows.map(r=>`<tr><td>#${r.id}</td><td>${esc(r.query)}</td><td>${esc(r.status)}</td><td>${r.next_search_page}</td><td><button onclick="resumeJob(${r.id})">Resume</button> ${keys.has('crawl:'+r.id)?`<button class="danger" onclick="cancelTask('crawl:${r.id}')">Cancel</button>`:''}</td></tr>`).join('');}
async function startJob(){const body={query:$('#jq').value,max_products:+$('#jlimit').value,max_search_pages:+$('#jpages').value};await api('/api/jobs',{method:'POST',body:JSON.stringify(body)});await jobs();await summary();}
async function resumeJob(id){await api(`/api/jobs/${id}/resume`,{method:'POST'});await jobs();}async function cancelTask(key){await api('/api/runtime/'+encodeURIComponent(key)+'/cancel',{method:'POST'});await jobs();}
async function watchlists(){const rows=await api('/api/watchlists');$('#watch-body').innerHTML=rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.query)}</td><td>${r.enabled?'on':'off'}</td><td>${r.interval_minutes}m</td><td>${esc(r.next_run_at)}</td><td><button onclick="runWatch(${r.id})">Run</button><button onclick="toggleWatch(${r.id},${!r.enabled})">${r.enabled?'Disable':'Enable'}</button></td></tr>`).join('');}
async function addWatch(){const body={name:$('#wname').value,query:$('#wquery').value,interval_minutes:+$('#wevery').value,max_products:+$('#wlimit').value,max_search_pages:+$('#wpages').value};await api('/api/watchlists',{method:'POST',body:JSON.stringify(body)});await watchlists();}
async function runWatch(id){await api(`/api/watchlists/${id}/run`,{method:'POST'});await watchlists();}async function toggleWatch(id,enabled){await api(`/api/watchlists/${id}`,{method:'PATCH',body:JSON.stringify({enabled})});await watchlists();}
async function alerts(){const rows=await api('/api/alerts');$('#alerts-body').innerHTML=rows.map(r=>`<tr><td>${esc(r.severity)}</td><td>${esc(r.title)}</td><td>${esc(r.message)}</td><td>${esc(r.created_at)}</td><td>${r.read_at?'read':`<button onclick="readAlert(${r.id})">Mark read</button>`}</td></tr>`).join('');}async function readAlert(id){await api(`/api/alerts/${id}/read`,{method:'POST'});await alerts();await summary();}
async function profiles(){const rows=await api('/api/scoring/profiles');$('#profiles-body').innerHTML=rows.map(r=>`<tr><td>${r.active?'★':''} ${esc(r.name)}</td><td>${r.price_weight}/${r.moq_weight}/${r.supplier_weight}/${r.tier_weight}/${r.data_quality_weight}</td><td>${r.min_score_alert}</td><td><button onclick="activateProfile(${r.id})">Activate</button></td></tr>`).join('');}
async function addProfile(){const body={name:$('#sname').value,price_weight:+$('#swp').value,moq_weight:+$('#swm').value,supplier_weight:+$('#sws').value,tier_weight:+$('#swt').value,data_quality_weight:+$('#swd').value,min_score_alert:+$('#salert').value,activate:true};await api('/api/scoring/profiles',{method:'POST',body:JSON.stringify(body)});await api('/api/scoring/rescore',{method:'POST',body:'{}'});await profiles();await summary();await products();}
async function activateProfile(id){await api(`/api/scoring/profiles/${id}/activate`,{method:'POST'});await api('/api/scoring/rescore',{method:'POST',body:'{}'});await profiles();await summary();await products();}
async function landed(){const ids=['currency','unit_price','quantity','shipping','insurance','duty_rate_pct','tax_rate_pct','brokerage','packaging_per_unit','other_fees','target_sale_price'];const body={};ids.forEach(k=>{const v=$('#lc-'+k).value;if(v!=='')body[k]=['currency'].includes(k)?v:+v});const r=await api('/api/landed-cost',{method:'POST',body:JSON.stringify(body)});$('#lc-result').textContent=JSON.stringify(r,null,2);}
async function refresh(){try{await Promise.all([summary(),products(),suppliers(),jobs(),watchlists(),alerts(),profiles()]);$('#status').textContent='connected';$('#status').className='ok';}catch(e){$('#status').textContent=e.message;$('#status').className='err';}}
window.productDetail=productDetail;window.supplierProducts=supplierProducts;window.resumeJob=resumeJob;window.cancelTask=cancelTask;window.runWatch=runWatch;window.toggleWatch=toggleWatch;window.readAlert=readAlert;window.activateProfile=activateProfile;
document.addEventListener('DOMContentLoaded',()=>{$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('#pfilter').onclick=products;$('#jstart').onclick=startJob;$('#wadd').onclick=addWatch;$('#sadd').onclick=addProfile;$('#lccalc').onclick=landed;tab('overview');refresh();setInterval(()=>{summary();jobs();alerts();},5000);});
"""

DASHBOARD_HTML = r"""<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AlibabaScraper</title><link rel="stylesheet" href="/assets/dashboard.css"></head><body><div class="wrap"><header><div class="brand"><h1>AlibabaScraper</h1><div class="muted">Sourcing intelligence control plane</div></div><div><span id="status">loading</span> · Profile <b id="profile-name">-</b></div></header><div class="grid"><div class="card metric"><span>Products</span><b id="m-products">-</b></div><div class="card metric"><span>Suppliers</span><b id="m-suppliers">-</b></div><div class="card metric"><span>Watchlists</span><b id="m-watchlists">-</b></div><div class="card metric"><span>Running</span><b id="m-running">-</b></div><div class="card metric"><span>Unread alerts</span><b id="m-alerts">-</b></div><div class="card metric"><span>Top score</span><b id="m-score">-</b></div></div><nav><button data-tab="overview">Products</button><button data-tab="suppliers">Suppliers</button><button data-tab="jobs">Jobs</button><button data-tab="watchlists">Watchlists</button><button data-tab="alerts">Alerts</button><button data-tab="scoring">Scoring</button><button data-tab="landed">Landed cost</button></nav>
<section data-panel="overview" class="panel"><div class="toolbar"><input id="pq" placeholder="product, ID, supplier"><input id="pmin" type="number" placeholder="min score"><input id="pmax" type="number" placeholder="max price"><input id="pcurrency" placeholder="currency"><button id="pfilter">Filter</button></div><div class="table-wrap"><table><thead><tr><th>Score</th><th>Product</th><th>Supplier</th><th>Price</th><th>MOQ</th><th></th></tr></thead><tbody id="products-body"></tbody></table></div><pre id="product-detail" class="result"></pre></section>
<section data-panel="suppliers" class="panel"><div class="table-wrap"><table><thead><tr><th>Supplier</th><th>Country</th><th>Products</th><th></th></tr></thead><tbody id="suppliers-body"></tbody></table></div><pre id="supplier-detail" class="result"></pre></section>
<section data-panel="jobs" class="panel"><div class="toolbar"><input id="jq" placeholder="new search query"><input id="jlimit" type="number" value="50"><input id="jpages" type="number" value="5"><button id="jstart">Start crawl</button></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Query</th><th>Status</th><th>Page</th><th>Control</th></tr></thead><tbody id="jobs-body"></tbody></table></div></section>
<section data-panel="watchlists" class="panel"><div class="toolbar"><input id="wname" placeholder="name"><input id="wquery" placeholder="query"><input id="wevery" type="number" value="1440"><input id="wlimit" type="number" value="50"><input id="wpages" type="number" value="5"><button id="wadd">Add watchlist</button></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Query</th><th>Enabled</th><th>Every</th><th>Next</th><th></th></tr></thead><tbody id="watch-body"></tbody></table></div></section>
<section data-panel="alerts" class="panel"><div class="table-wrap"><table><thead><tr><th>Level</th><th>Title</th><th>Message</th><th>Time</th><th></th></tr></thead><tbody id="alerts-body"></tbody></table></div></section>
<section data-panel="scoring" class="panel"><div class="forms"><label>Name<input id="sname" value="My profile"></label><label>Alert score<input id="salert" type="number" value="85"></label><label>Price weight<input id="swp" type="number" value="35"></label><label>MOQ weight<input id="swm" type="number" value="20"></label><label>Supplier weight<input id="sws" type="number" value="20"></label><label>Tier discount weight<input id="swt" type="number" value="10"></label><label>Data quality weight<input id="swd" type="number" value="15"></label><div><button id="sadd">Create + activate + rescore</button></div></div><div class="table-wrap"><table><thead><tr><th>Profile</th><th>Weights P/M/S/T/D</th><th>Alert ≥</th><th></th></tr></thead><tbody id="profiles-body"></tbody></table></div></section>
<section data-panel="landed" class="panel"><div class="forms"><label>Currency<input id="lc-currency" value="USD"></label><label>Unit price<input id="lc-unit_price" type="number" step="0.01"></label><label>Quantity<input id="lc-quantity" type="number" value="1"></label><label>Shipping<input id="lc-shipping" type="number" value="0"></label><label>Insurance<input id="lc-insurance" type="number" value="0"></label><label>Duty %<input id="lc-duty_rate_pct" type="number" value="0"></label><label>Tax %<input id="lc-tax_rate_pct" type="number" value="0"></label><label>Brokerage<input id="lc-brokerage" type="number" value="0"></label><label>Packaging/unit<input id="lc-packaging_per_unit" type="number" value="0"></label><label>Other fees<input id="lc-other_fees" type="number" value="0"></label><label>Target sale price<input id="lc-target_sale_price" type="number"></label><div><button id="lccalc">Calculate</button></div></div><p class="muted">Generic estimate using the rates and fees you provide; jurisdiction-specific customs/tax rules are not inferred.</p><pre id="lc-result" class="result"></pre></section></div><script src="/assets/dashboard.js"></script></body></html>"""
